services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: tea_tracker
      POSTGRES_USER: tea_tracker
      POSTGRES_PASSWORD: tea_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build:
      context: ..
      dockerfile: ./docker/service.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  ui:
    build:
      context: ..
      dockerfile: ./docker/ui.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - service

volumes:
  postgres_data:
